apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    appstudio.openshift.io/application: integ-app-ckom
    appstudio.openshift.io/component: integration-suite-test-component-git-source-ccoe
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: integration-suite-test-component-git-source-ccoe
  namespace: integration-e2e-qyrd
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: integration-suite-test-component-git-source-ccoe
status:
  configuration:
    generatedName: ""
